on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Mattermost
      run: |
        echo "{\"text\":\"Something new was pushed to [toolbox](https://github.com/kit-cn-cms/toolbox) :tada:\"}" > mattermost.json
    - uses: mattermost/action-mattermost-notify@1.0.2
      env:
        MATTERMOST_WEBHOOK_URL: https://mattermost.web.cern.ch/hooks/8t1opxha5bd4xr5iifd63eajkc
